version: '3'

services:
    web:
        image: cheaterman/flask
        ports:
            - 127.0.0.1:5000:5000
        volumes:
            - .:/code
        environment:
            WSGI_MODULE: floceries:app
